import * as v from 'valibot';
import { slugify } from '../../slug';
import { tagSchema } from '../content/schemas';

/**
 * Starter tags, loaded with `bun run db:seed-tags`.
 *
 * Additive only: the seed never deletes a tag or renames one the editor chose,
 * so it is safe to run again after this list grows. A tag with fewer than three
 * articles is noindexed and left out of the sitemap (PRD §12.7), so an unused
 * tag here costs nothing in search.
 *
 * Slugs are explicit wherever the generated one would be wrong or would
 * collide — "C++" and "C#" both slugify to "c".
 */
export type TagSeed = { name: string; slug?: string };

export const TAG_GROUPS: Record<string, TagSeed[]> = {
	'AI companies': [
		{ name: 'OpenAI' },
		{ name: 'Anthropic' },
		{ name: 'Google DeepMind' },
		{ name: 'Meta AI' },
		{ name: 'Microsoft' },
		{ name: 'xAI', slug: 'xai' },
		{ name: 'Mistral AI' },
		{ name: 'DeepSeek' },
		{ name: 'Alibaba Cloud' },
		{ name: 'Moonshot AI' },
		{ name: 'Z.ai', slug: 'zai' },
		{ name: 'MiniMax' },
		{ name: 'Perplexity' },
		{ name: 'Hugging Face' },
		{ name: 'Nvidia' },
		{ name: 'Cohere' },
		{ name: 'Stability AI' },
		{ name: 'ElevenLabs' },
		{ name: 'Runway' }
	],
	'AI products and models': [
		{ name: 'ChatGPT' },
		{ name: 'GPT', slug: 'gpt' },
		{ name: 'Claude' },
		{ name: 'Claude Code' },
		{ name: 'Gemini' },
		{ name: 'Grok' },
		{ name: 'Llama' },
		{ name: 'Qwen' },
		{ name: 'Kimi' },
		{ name: 'GLM', slug: 'glm' },
		{ name: 'Codex' },
		{ name: 'GitHub Copilot' },
		{ name: 'Microsoft Copilot' },
		{ name: 'Cursor' },
		{ name: 'Windsurf' },
		{ name: 'Gemini CLI' },
		{ name: 'NotebookLM', slug: 'notebooklm' },
		{ name: 'Midjourney' },
		{ name: 'Stable Diffusion' },
		{ name: 'Flux' },
		{ name: 'Sora' },
		{ name: 'Veo' },
		{ name: 'Suno' },
		{ name: 'Apple Intelligence' }
	],
	'AI concepts': [
		{ name: 'LLM', slug: 'llm' },
		{ name: 'AI Agents' },
		{ name: 'AI Coding' },
		{ name: 'Prompt Engineering' },
		{ name: 'RAG', slug: 'rag' },
		{ name: 'Open Models' },
		{ name: 'Local AI' },
		{ name: 'Multimodal AI' },
		{ name: 'Reasoning Models' },
		{ name: 'Image Generation' },
		{ name: 'Video Generation' },
		{ name: 'Voice AI' },
		{ name: 'Computer Use' },
		{ name: 'MCP', slug: 'mcp' },
		{ name: 'Fine-Tuning' },
		{ name: 'Embeddings' },
		{ name: 'Vector Databases' },
		{ name: 'Context Window' },
		{ name: 'AI Benchmarks' },
		{ name: 'AI Pricing' },
		{ name: 'AI Safety' },
		{ name: 'AGI', slug: 'agi' },
		{ name: 'AI Search' },
		{ name: 'Chatbots' },
		{ name: 'Automation' },
		{ name: 'No-Code' }
	],
	'Languages and frameworks': [
		{ name: 'JavaScript' },
		{ name: 'TypeScript' },
		{ name: 'Python' },
		{ name: 'Rust' },
		{ name: 'Go', slug: 'golang' },
		{ name: 'Java' },
		{ name: 'Kotlin' },
		{ name: 'Swift' },
		{ name: 'PHP', slug: 'php' },
		{ name: 'C++', slug: 'cpp' },
		{ name: 'C#', slug: 'csharp' },
		{ name: 'Svelte' },
		{ name: 'SvelteKit' },
		{ name: 'React' },
		{ name: 'Next.js', slug: 'nextjs' },
		{ name: 'Vue', slug: 'vue' },
		{ name: 'Nuxt' },
		{ name: 'Angular' },
		{ name: 'Astro' },
		{ name: 'Tailwind CSS' },
		{ name: 'Node.js', slug: 'nodejs' },
		{ name: 'Bun' },
		{ name: 'Deno' },
		{ name: 'Laravel' },
		{ name: 'Django' },
		{ name: 'FastAPI', slug: 'fastapi' },
		{ name: 'Flutter' },
		{ name: 'React Native' }
	],
	'Developer tools and infrastructure': [
		{ name: 'Developer Tools' },
		{ name: 'Web Development' },
		{ name: 'Frontend' },
		{ name: 'Backend' },
		{ name: 'Mobile Development' },
		{ name: 'Open Source' },
		{ name: 'Git' },
		{ name: 'GitHub' },
		{ name: 'VS Code', slug: 'vscode' },
		{ name: 'JetBrains' },
		{ name: 'Neovim' },
		{ name: 'Terminal' },
		{ name: 'Docker' },
		{ name: 'Kubernetes' },
		{ name: 'Linux' },
		{ name: 'Ubuntu' },
		{ name: 'Self-Hosting' },
		{ name: 'PostgreSQL', slug: 'postgresql' },
		{ name: 'SQLite', slug: 'sqlite' },
		{ name: 'Redis' },
		{ name: 'Databases' },
		{ name: 'Supabase' },
		{ name: 'Firebase' },
		{ name: 'Cloudflare' },
		{ name: 'Vercel' },
		{ name: 'AWS', slug: 'aws' },
		{ name: 'Google Cloud' },
		{ name: 'Azure' },
		{ name: 'Serverless' },
		{ name: 'DevOps' },
		{ name: 'CI/CD', slug: 'ci-cd' },
		{ name: 'Testing' },
		{ name: 'APIs', slug: 'apis' },
		{ name: 'Web Performance' }
	],
	'Security and privacy': [
		{ name: 'Cybersecurity' },
		{ name: 'Privacy' },
		{ name: 'Vulnerabilities' },
		{ name: 'Malware' },
		{ name: 'Passkeys' }
	],
	'Devices and platforms': [
		{ name: 'Gadgets' },
		{ name: 'Smartphones' },
		{ name: 'Android' },
		{ name: 'iPhone', slug: 'iphone' },
		{ name: 'iOS', slug: 'ios' },
		{ name: 'macOS', slug: 'macos' },
		{ name: 'Windows' },
		{ name: 'Laptops' },
		{ name: 'Tablets' },
		{ name: 'Wearables' },
		{ name: 'Smart Home' },
		{ name: 'VR and AR', slug: 'vr-ar' },
		{ name: 'Apple' },
		{ name: 'Google' },
		{ name: 'Samsung' },
		{ name: 'Xiaomi' },
		{ name: 'Google Pixel' },
		{ name: 'Chips' },
		{ name: 'AMD', slug: 'amd' },
		{ name: 'Intel' },
		{ name: 'Qualcomm' },
		{ name: 'Apple Silicon' }
	],
	'Apps and internet': [
		{ name: 'YouTube' },
		{ name: 'TikTok' },
		{ name: 'Instagram' },
		{ name: 'WhatsApp' },
		{ name: 'X (Twitter)', slug: 'x-twitter' },
		{ name: 'Social Media' },
		{ name: 'Productivity' },
		{ name: 'Startups' },
		{ name: 'E-commerce' },
		{ name: 'Indonesia' }
	],
	'Games and esports': [
		{ name: 'Gaming' },
		{ name: 'Esports' },
		{ name: 'PC Gaming' },
		{ name: 'Mobile Gaming' },
		{ name: 'PlayStation' },
		{ name: 'Xbox' },
		{ name: 'Nintendo' },
		{ name: 'Steam' },
		{ name: 'Game Development' },
		{ name: 'Unity' },
		{ name: 'Unreal Engine' },
		{ name: 'Dota 2' },
		{ name: 'Mobile Legends' },
		{ name: 'Valorant' },
		{ name: 'Counter-Strike 2' },
		{ name: 'League of Legends' },
		{ name: 'PUBG Mobile', slug: 'pubg-mobile' },
		{ name: 'Free Fire' },
		{ name: 'Genshin Impact' },
		{ name: 'Honkai: Star Rail' },
		{ name: 'Minecraft' },
		{ name: 'Roblox' },
		{ name: 'GTA VI', slug: 'gta-6' }
	],
	Entertainment: [
		{ name: 'K-Drama' },
		{ name: 'K-Pop' },
		{ name: 'Anime' },
		{ name: 'Netflix' },
		{ name: 'Streaming' },
		{ name: 'Spotify' }
	],
	'More AI companies and tools': [
		{ name: 'Amazon' },
		{ name: 'IBM' },
		{ name: 'Adobe' },
		{ name: 'Baidu' },
		{ name: 'ByteDance' },
		{ name: 'Tencent' },
		{ name: 'Scale AI' },
		{ name: 'Character.AI', slug: 'character-ai' },
		{ name: 'Replit' },
		{ name: 'Notion' },
		{ name: 'Canva' },
		{ name: 'Figma' },
		{ name: 'Lovable' },
		{ name: 'Bolt.new', slug: 'bolt-new' },
		{ name: 'v0', slug: 'v0' },
		{ name: 'Gemma' },
		{ name: 'Devin' },
		{ name: 'Aider' },
		{ name: 'Cline' },
		{ name: 'OpenCode' },
		{ name: 'Zed' },
		{ name: 'Google AI Studio', slug: 'google-ai-studio' },
		{ name: 'Ollama' },
		{ name: 'LM Studio' },
		{ name: 'OpenRouter' },
		{ name: 'LangChain' },
		{ name: 'LlamaIndex' },
		{ name: 'PyTorch' },
		{ name: 'TensorFlow' },
		{ name: 'vLLM', slug: 'vllm' },
		{ name: 'llama.cpp', slug: 'llama-cpp' },
		{ name: 'ComfyUI' },
		{ name: 'n8n', slug: 'n8n' },
		{ name: 'Zapier' },
		{ name: 'Adobe Firefly' },
		{ name: 'Ideogram' },
		{ name: 'Leonardo AI' },
		{ name: 'Kling' },
		{ name: 'Pika' },
		{ name: 'Luma AI' },
		{ name: 'Udio' },
		{ name: 'Whisper' }
	],
	'More AI topics': [
		{ name: 'Machine Learning' },
		{ name: 'Deep Learning' },
		{ name: 'Transformer Models' },
		{ name: 'AI Ethics' },
		{ name: 'Deepfakes' },
		{ name: 'AI Copyright' },
		{ name: 'Synthetic Data' },
		{ name: 'AI Evaluation' },
		{ name: 'AI Hallucinations' },
		{ name: 'Quantization' },
		{ name: 'GPU Computing' },
		{ name: 'On-Device AI' },
		{ name: 'Edge AI' },
		{ name: 'Speech Recognition' },
		{ name: 'Text-to-Speech' },
		{ name: 'AI Translation' },
		{ name: 'OCR', slug: 'ocr' },
		{ name: 'Recommendation Systems' },
		{ name: 'Robotics' },
		{ name: 'Humanoid Robots' },
		{ name: 'Autonomous Vehicles' },
		{ name: 'AI in Education' },
		{ name: 'AI for Work' }
	],
	'More technology': [
		{ name: 'Data Centers' },
		{ name: 'Cloud Computing' },
		{ name: 'Quantum Computing' },
		{ name: '5G', slug: '5g' },
		{ name: 'Starlink' },
		{ name: 'Space Tech' },
		{ name: 'Electric Vehicles' },
		{ name: 'Tesla' },
		{ name: 'BYD', slug: 'byd' },
		{ name: 'Batteries' },
		{ name: 'Drones' },
		{ name: '3D Printing' },
		{ name: 'Browsers' },
		{ name: 'Chrome' },
		{ name: 'Firefox' },
		{ name: 'Safari' },
		{ name: 'Email' },
		{ name: 'Password Managers' },
		{ name: 'VPN', slug: 'vpn' },
		{ name: 'Raspberry Pi' },
		{ name: 'Arduino' },
		{ name: 'Homelab' },
		{ name: 'NAS', slug: 'nas' },
		{ name: 'Networking' },
		{ name: 'Wi-Fi' },
		{ name: 'Monitors' },
		{ name: 'Keyboards' },
		{ name: 'Headphones' },
		{ name: 'Photography' },
		{ name: 'GPUs', slug: 'gpus' },
		{ name: 'PC Building' },
		{ name: 'Gaming Laptops' },
		{ name: 'Chromebook' },
		{ name: 'HarmonyOS' },
		{ name: 'Huawei' },
		{ name: 'OPPO', slug: 'oppo' },
		{ name: 'vivo' },
		{ name: 'realme' },
		{ name: 'Infinix' },
		{ name: 'OnePlus' },
		{ name: 'Nothing Phone', slug: 'nothing-phone' },
		{ name: 'Apple Watch' },
		{ name: 'iPad' },
		{ name: 'MacBook' },
		{ name: 'Arch Linux' },
		{ name: 'Fedora' },
		{ name: 'Debian' },
		{ name: 'Windows 11' }
	],
	'More software development': [
		{ name: 'Ruby' },
		{ name: 'Ruby on Rails', slug: 'rails' },
		{ name: 'Elixir' },
		{ name: 'Zig' },
		{ name: 'Dart' },
		{ name: 'Lua' },
		{ name: 'SQL', slug: 'sql' },
		{ name: 'GraphQL' },
		{ name: 'WebAssembly' },
		{ name: 'HTMX', slug: 'htmx' },
		{ name: 'SolidJS', slug: 'solidjs' },
		{ name: 'Remix' },
		{ name: 'Express.js', slug: 'expressjs' },
		{ name: 'NestJS' },
		{ name: 'Hono' },
		{ name: 'Spring Boot' },
		{ name: '.NET', slug: 'dotnet' },
		{ name: 'Tauri' },
		{ name: 'Electron' },
		{ name: 'Expo' },
		{ name: 'Jetpack Compose' },
		{ name: 'SwiftUI' },
		{ name: 'Prisma' },
		{ name: 'Drizzle ORM' },
		{ name: 'MongoDB' },
		{ name: 'MySQL' },
		{ name: 'Elasticsearch' },
		{ name: 'Kafka' },
		{ name: 'Nginx' },
		{ name: 'Caddy' },
		{ name: 'Terraform' },
		{ name: 'Ansible' },
		{ name: 'Observability' },
		{ name: 'Sentry' },
		{ name: 'Playwright' },
		{ name: 'Vitest' },
		{ name: 'Jest' },
		{ name: 'UI Design' },
		{ name: 'UX', slug: 'ux' },
		{ name: 'Accessibility' },
		{ name: 'CSS', slug: 'css' },
		{ name: 'HTML', slug: 'html' },
		{ name: 'Browser Extensions' },
		{ name: 'CLI Tools' },
		{ name: 'Shell Scripting', slug: 'shell' },
		{ name: 'System Design' },
		{ name: 'Software Architecture' },
		{ name: 'Code Review' },
		{ name: 'Tech Careers', slug: 'tech-careers' },
		{ name: 'Remote Work' },
		{ name: 'Coding Interviews' }
	],
	'More security': [
		{ name: 'Phishing' },
		{ name: 'Ransomware' },
		{ name: 'Data Breaches' },
		{ name: 'Encryption' },
		{ name: 'Two-Factor Authentication', slug: '2fa' },
		{ name: 'Online Scams' }
	],
	'More apps and internet': [
		{ name: 'Telegram' },
		{ name: 'Discord' },
		{ name: 'Threads' },
		{ name: 'Bluesky' },
		{ name: 'Reddit' },
		{ name: 'LinkedIn' },
		{ name: 'Gmail' },
		{ name: 'Google Maps' },
		{ name: 'Google Search' },
		{ name: 'Shopee' },
		{ name: 'Tokopedia' },
		{ name: 'Gojek' },
		{ name: 'Grab' },
		{ name: 'Traveloka' },
		{ name: 'Online Learning' },
		{ name: 'Podcasts' },
		{ name: 'Content Creators' }
	],
	'More games and esports': [
		{ name: 'PlayStation 5', slug: 'ps5' },
		{ name: 'Xbox Game Pass' },
		{ name: 'Steam Deck' },
		{ name: 'Handheld PCs' },
		{ name: 'Epic Games' },
		{ name: 'Riot Games' },
		{ name: 'Valve' },
		{ name: 'Moonton' },
		{ name: 'Garena' },
		{ name: 'HoYoverse' },
		{ name: 'Call of Duty' },
		{ name: 'Call of Duty: Mobile' },
		{ name: 'Fortnite' },
		{ name: 'Apex Legends' },
		{ name: 'Overwatch 2' },
		{ name: 'Honor of Kings' },
		{ name: 'Wuthering Waves' },
		{ name: 'Zenless Zone Zero' },
		{ name: 'Elden Ring' },
		{ name: 'The Legend of Zelda' },
		{ name: 'Pokémon' },
		{ name: 'EA Sports FC' },
		{ name: 'eFootball' },
		{ name: 'Clash of Clans' },
		{ name: 'Clash Royale' },
		{ name: 'Brawl Stars' },
		{ name: 'Stardew Valley' },
		{ name: 'Hollow Knight' },
		{ name: 'Monster Hunter' },
		{ name: 'Final Fantasy' },
		{ name: 'Resident Evil' },
		{ name: 'Cyberpunk 2077' },
		{ name: 'The Witcher' },
		{ name: 'Indie Games' },
		{ name: 'Speedrunning' },
		{ name: 'MPL Indonesia', slug: 'mpl-indonesia' },
		{ name: 'The International' },
		{ name: 'Valorant Champions Tour', slug: 'vct' },
		{ name: 'Game Streaming' },
		{ name: 'Twitch' },
		{ name: 'Cloud Gaming' },
		{ name: 'Retro Gaming' }
	],
	'More entertainment': [
		{ name: 'Film' },
		{ name: 'TV Series' },
		{ name: 'Manga' },
		{ name: 'Webtoon' },
		{ name: 'Marvel' },
		{ name: 'Star Wars' },
		{ name: 'Disney+', slug: 'disney-plus' },
		{ name: 'Prime Video' },
		{ name: 'Vidio' },
		{ name: 'Viu' },
		{ name: 'Crunchyroll' },
		{ name: 'J-Pop' },
		{ name: 'C-Drama' },
		{ name: 'Film Indonesia' },
		{ name: 'Cosplay' },
		{ name: 'Pop Culture' }
	],
	Formats: [{ name: 'Comparison' }, { name: 'Guide' }, { name: 'Explainer' }]
};

/**
 * The list as rows to insert, validated by the same schema as the admin form.
 * Throws on a duplicate slug rather than letting the second silently win.
 */
export function resolveTags(): { slug: string; name: string }[] {
	const seen = new Map<string, string>();
	const rows: { slug: string; name: string }[] = [];

	for (const seed of Object.values(TAG_GROUPS).flat()) {
		const row = v.parse(tagSchema, { name: seed.name, slug: seed.slug ?? slugify(seed.name) });
		const clash = seen.get(row.slug);
		if (clash) throw new Error(`"${seed.name}" and "${clash}" share the slug "${row.slug}"`);
		seen.set(row.slug, seed.name);
		rows.push(row);
	}
	return rows;
}
